# SITE CONFIGURATION
baseurl: "/blog"
url: "https://faraazahmad.github.io"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Frugal Code
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text: >
     <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>

     <p>Remove all header text in <code>_config.yml</code> to disable this feature.</p>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/rohanchandra/type-theme">Type Theme</a>

  # Icons
  rss: false
  email_address: faraaz98@live.com # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "faraazahmad"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "faraaz98"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  search: true # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
theme: jekyll-theme-type
exclude:
  - Gemfile
  - Gemfile.lock
=======
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Wheel # ex. I m Chuan
name: Syed Faraaz Ahmad # ex. DONGChuan
email: faraaz98@live.com
location: New Delhi, India # ex. Nice, France
company: # none
company_url: # none
github_url: https://github.com/faraazahmad/ # ex. https://github.com/DONGChuan
github_username: faraazahmad # ex. DONGChuan
description: description_of_your_web_site
favicon: favicon.png # Image must be in assets/images
repository: faraazahmad/faraazahmad.github.io/blog/ # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
baseurl: /blog
url: https://faraazahmad.github.io/

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /posts
    label: Blog

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, C, C++, Qt, Python, MySQL, Oracle, SQLite, PL/SQL, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]
